language: generic
sudo: required # We give admin right
services: # We indicate to travis to install a copy of docker in our running container
  - docker

script: # Every commands needed to run the test
  - docker-compose build

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "simpleflaskapp" # Name application on Elastic beanstalk
  env: "Simpleflaskapp-env" # Name environment on Elastic beanstalk
  bucket_name: "elasticbeanstalk-eu-west-3-120100701306"
  bucket_path: "simpleflaskapp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  script: docker-compose up
